### ISSUE TITLE
Mode 4: Smart Mode

### ISSUE THREAD

**Issue by MariusWirtz** [MariusWirtz/optimus-py#1]
Implement the `SmartMode`

Approach:
- Measure how every dimension behaves as the first dimension. Find dimension that has the best  query speed as the first dimension
- then do the same thing for position 2 to n
- Once the changes from n to  n + 1 are becoming insignificant abort

**Comment by scrumthing** [comment]
@MariusWirtz Very cool idea. If we find some time lets chat about your approach. Would love to hear more about your thinking process. If that works it could be a real game changer.

**Comment by MariusWirtz** [comment]
Thank you. All credit for this idea goes to @cubewise-tryan!

I have it like half-way implemented on my local branch. I will finish and push it in the next days. I'm curious to compare the results of this approach with the other approaches. Happy to have a discussion about it!

**Comment by MariusWirtz** [comment]
Implemented as `best` mode.

![image](https://user-images.githubusercontent.com/15182131/88581962-43199d00-d04e-11ea-9f76-4d95d9bb5655.png)
